



server:
  port: 9090



spring:
  datasource:
    driver-class-name: org.apache.derby.jdbc.EmbeddedDriver
    url: jdbc:derby:memory:myDB;create=true
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.DerbyTenSevenDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.DerbyTenSevenDialect



mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



logging:
  level:
    root: info