package com.zsx.springbootderby.dao;

import com.zsx.springbootderby.entity.User;
import org.apache.ibatis.annotations.*;
import org.springframework.jdbc.BadSqlGrammarException;

import java.util.List;

/**
 * @Date 2019/7/30 15:32
 **/
@Mapper
public interface UserDao {

//    这种可以指定主键插入数据，但下面那种不能指定主键id
//    @Update("create table t_user(id int generated by default as identity(start with 1, increment by 1), name varchar(50), pwd varchar(100))")
//
    @Update("create table t_user(id int generated always as identity, name varchar(50), pwd varchar(100))")
    void create() throws Exception;

    @Select("select count(1) from t_user")
    Integer count() throws BadSqlGrammarException;

    @Select("select * from t_user")
    List<User> selectAll() throws Exception;

    @Select("select * from t_user order by id asc {limit ${limit} offset ${offset}}")
    List<User> selectPage(@Param("limit") int limit, @Param("offset") int offset) throws Exception;

    @Insert("insert into t_user(name,pwd) values(#{o.name}, #{o.pwd})")
    void insert(@Param("o") User obj) throws Exception;

    @Delete("<script>delete from t_user where id in <foreach item='item' index='index' collection='ids' open='(' separator=',' close=')'>#{item}</foreach></script>")
    void delete(@Param("ids") List<String> ids) throws Exception;

    @Update("update t_user set name = #{o.name}, pwd = #{o.pwd} where id = #{o.id}")
    void update(@Param("o") User obj) throws Exception;
}
